# NOTICE: Generated By HttpRunner v3.0.8
# FROM: testcases/demo_testcase_ref.yml

import os
import sys

sys.path.insert(0, os.getcwd())

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.demo_testcase_request_test import (
    TestCaseDemoTestcaseRequest as DemoTestcaseRequest,
)


class TestCaseDemoTestcaseRef(HttpRunner):
    config = (
        Config("request methods testcase: reference testcase")
        .variables(**{"foo1": "session_bar1"})
        .base_url("https://postman-echo.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunTestCase("request with referenced testcase")
            .with_variables(**{"foo1": "override_bar1"})
            .call(DemoTestcaseRequest)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseRef().test_start()
