# NOTE: Generated By HttpRunner v3.0.10
# FROM: testcases/mubu.createdoc.yml

import os
import sys

sys.path.insert(0, os.getcwd())

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.mubu_login_test import TestCaseMubuLogin as MubuLogin


class TestCaseMubuCreatedoc(HttpRunner):
    config = (
        Config("testcase description")
        .variables(**{"user_phone": 18810143184, "password": "lm920805"})
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("mubu login").call(MubuLogin)),
        Step(
            RunRequest("/api/list/create_doc")
            .post("https://mubu.com/api/list/create_doc")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "17",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_data({"folderId": "0", "type": "0"})
            .extract()
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc$docId")
            .get("https://mubu.com/doc$docId")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html; charset=utf-8")
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .post("https://api2.mubu.com/v3/api/document/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "23",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "b9ca6b54-f454-4f10-bfed-6024559a41e0",
                }
            )
            .with_json({"docId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "29",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "45a90180-b0ef-469b-8952-577fb76a4c2e",
                }
            )
            .with_json({"document_id": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "OK")
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .post("https://api2.mubu.com/v3/api/user/current_user")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "c9e0e85c-6fec-49a5-92ab-099e9a8c1207",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.mubu.com/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "ccc44205-23a4-40be-9222-1ebf4707dec7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "e8b0c0c6-5174-4d36-aa19-63ccb35ce8cc",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "Success")
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "ca84c363-51bb-4ad1-9f8a-41963c36a955",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"documentId": "$docId", "memberId": "5245182482027341"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Access-Control-Request-Headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "Access-Control-Request-Method": "GET",
                    "Connection": "keep-alive",
                    "Host": "api2.mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/plain; charset=utf-8")
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"documentId": "$docId", "memberId": "5245182482027341"})
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "members:5245182482027341:1591502419528",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "10376703-c14f-479f-b569-0af8ad52186f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "425",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:4",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "e3995710-145b-4782-b04f-72e0b998da40",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {"name": "nameChanged", "original": "", "title": "d"},
                                {"name": "nameChanged", "original": "d", "title": "de"},
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 0,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 4,
                    "requestId": "MESSAGE:6939472:5245182482027341:4",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "378",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:6",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "9ec7c081-d093-404e-8c60-f2135fba9dcd",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "original": "de",
                                    "title": "dem",
                                }
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 1,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 6,
                    "requestId": "MESSAGE:6939472:5245182482027341:6",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "437",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:8",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "e0ca8130-1abd-4956-9970-60e08c3c0f82",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "original": "dem",
                                    "title": "demo",
                                },
                                {
                                    "name": "nameChanged",
                                    "original": "demo",
                                    "title": "demo1",
                                },
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 2,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 8,
                    "requestId": "MESSAGE:6939472:5245182482027341:8",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "502",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:10",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "0ea321c4-ed52-4e2a-92cf-85c94d450995",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "created": [
                                        {
                                            "index": 0,
                                            "node": {
                                                "children": [],
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502440122,
                                                "text": "",
                                            },
                                            "parentId": None,
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                    "name": "create",
                                }
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 3,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 10,
                    "requestId": "MESSAGE:6939472:5245182482027341:10",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "567",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:12",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "796a7bd4-e74e-4077-9f16-3a9bf60adf45",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502440122,
                                                "text": "",
                                            },
                                            "path": ["nodes", 0],
                                            "updated": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502441053,
                                                "text": "<span>l</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 4,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 12,
                    "requestId": "MESSAGE:6939472:5245182482027341:12",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "583",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:14",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "db581453-0c3a-49f1-9e2f-8c12dd9e05be",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502441053,
                                                "text": "<span>l</span>",
                                            },
                                            "path": ["nodes", 0],
                                            "updated": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502441719,
                                                "text": "<span>lin</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 5,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 14,
                    "requestId": "MESSAGE:6939472:5245182482027341:14",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "587",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Member-Id": "5245182482027341",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Request-Id": "MESSAGE:6939472:5245182482027341:16",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "47af1c05-7642-43a6-9e74-02d880583640",
                }
            )
            .with_json(
                {
                    "context": {
                        "appVersion": "1.0.0.81",
                        "os": "macOS",
                        "osVersion": "10.15.4",
                        "platform": "web",
                    },
                    "data": {
                        "message": {
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "original": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502441719,
                                                "text": "<span>lin</span>",
                                            },
                                            "path": ["nodes", 0],
                                            "updated": {
                                                "id": "6a6f637495d4f3d5bb0cefa094c5ecbf",
                                                "modified": 1591502442581,
                                                "text": "<span>line1</span>",
                                            },
                                        }
                                    ],
                                }
                            ],
                            "documentId": "$docId",
                            "type": "CHANGE",
                            "version": 6,
                            "viewType": "OUTLINE",
                        }
                    },
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 16,
                    "requestId": "MESSAGE:6939472:5245182482027341:16",
                    "token": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v3/api/document/get_recent_list")
            .post("https://api2.mubu.com/v3/api/document/get_recent_list")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "42",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "x-request-id": "78352933-81bc-4d5c-a3f2-a9c894621144",
                }
            )
            .with_json({"documentId": "$docId", "keywords": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("https://mubu.com/list")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Cookie": "_ga=GA1.2.2133272746.1586684123; s_v_web_id=k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS; data_unique_id=9e1dc484-873c-43f5-9b4a-b8e13cdba386; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1591257799; mubu_inner=1; reg_entrance=https%3A%2F%2Fmubu.com%2Flist; _gid=GA1.2.725287396.1591499748; language=en-US; country=US; csrf_token=33781c0f-249a-4681-ad92-7db4bf319d01; data-unique-id=3985b1f0-a873-11ea-a35b-15f69595a402; SESSION=ab65b4c6-548c-4729-92fa-973de8afe03e; reg_prepareId=1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79; reg_focusId=f946fd06-fc70-4a7c-a5ce-1728ceeffdf; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q; user_persistence=$user_persistence; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1591502380; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/doc$docId",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1591502380",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1591257799",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "SESSION": "ab65b4c6-548c-4729-92fa-973de8afe03e",
                    "SLARDAR_WEB_ID": "b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "_ga": "GA1.2.2133272746.1586684123",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.725287396.1591499748",
                    "country": "US",
                    "csrf_token": "33781c0f-249a-4681-ad92-7db4bf319d01",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "data_unique_id": "9e1dc484-873c-43f5-9b4a-b8e13cdba386",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "reg_focusId": "f946fd06-fc70-4a7c-a5ce-1728ceeffdf",
                    "reg_prepareId": "1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79",
                    "s_v_web_id": "k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS",
                    "user_persistence": "$user_persistence",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("https://mubu.com/api/list/tip_new_update")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.2133272746.1586684123; s_v_web_id=k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS; data_unique_id=9e1dc484-873c-43f5-9b4a-b8e13cdba386; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1591257799; mubu_inner=1; reg_entrance=https%3A%2F%2Fmubu.com%2Flist; _gid=GA1.2.725287396.1591499748; language=en-US; country=US; csrf_token=33781c0f-249a-4681-ad92-7db4bf319d01; data-unique-id=3985b1f0-a873-11ea-a35b-15f69595a402; SESSION=ab65b4c6-548c-4729-92fa-973de8afe03e; reg_prepareId=1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79; reg_focusId=f946fd06-fc70-4a7c-a5ce-1728ceeffdf; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q; user_persistence=$user_persistence; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1591502380; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1591502380",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1591257799",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "SESSION": "ab65b4c6-548c-4729-92fa-973de8afe03e",
                    "SLARDAR_WEB_ID": "b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "_ga": "GA1.2.2133272746.1586684123",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.725287396.1591499748",
                    "country": "US",
                    "csrf_token": "33781c0f-249a-4681-ad92-7db4bf319d01",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "data_unique_id": "9e1dc484-873c-43f5-9b4a-b8e13cdba386",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "reg_focusId": "f946fd06-fc70-4a7c-a5ce-1728ceeffdf",
                    "reg_prepareId": "1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79",
                    "s_v_web_id": "k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS",
                    "user_persistence": "$user_persistence",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("https://mubu.com/api/list/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "_ga=GA1.2.2133272746.1586684123; s_v_web_id=k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS; data_unique_id=9e1dc484-873c-43f5-9b4a-b8e13cdba386; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1591257799; mubu_inner=1; reg_entrance=https%3A%2F%2Fmubu.com%2Flist; _gid=GA1.2.725287396.1591499748; language=en-US; country=US; csrf_token=33781c0f-249a-4681-ad92-7db4bf319d01; data-unique-id=3985b1f0-a873-11ea-a35b-15f69595a402; SESSION=ab65b4c6-548c-4729-92fa-973de8afe03e; reg_prepareId=1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79; reg_focusId=f946fd06-fc70-4a7c-a5ce-1728ceeffdf; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q; user_persistence=$user_persistence; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1591502380; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1591502380",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1591257799",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "SESSION": "ab65b4c6-548c-4729-92fa-973de8afe03e",
                    "SLARDAR_WEB_ID": "b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "_ga": "GA1.2.2133272746.1586684123",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.725287396.1591499748",
                    "country": "US",
                    "csrf_token": "33781c0f-249a-4681-ad92-7db4bf319d01",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "data_unique_id": "9e1dc484-873c-43f5-9b4a-b8e13cdba386",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "reg_focusId": "f946fd06-fc70-4a7c-a5ce-1728ceeffdf",
                    "reg_prepareId": "1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79",
                    "s_v_web_id": "k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS",
                    "user_persistence": "$user_persistence",
                }
            )
            .with_data({"folderId": "0", "keywords": "", "sort": "time", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("https://mubu.com/api/message/get_message_unread")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Cookie": "_ga=GA1.2.2133272746.1586684123; s_v_web_id=k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS; data_unique_id=9e1dc484-873c-43f5-9b4a-b8e13cdba386; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1591257799; mubu_inner=1; reg_entrance=https%3A%2F%2Fmubu.com%2Flist; _gid=GA1.2.725287396.1591499748; language=en-US; country=US; csrf_token=33781c0f-249a-4681-ad92-7db4bf319d01; data-unique-id=3985b1f0-a873-11ea-a35b-15f69595a402; SESSION=ab65b4c6-548c-4729-92fa-973de8afe03e; reg_prepareId=1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79; reg_focusId=f946fd06-fc70-4a7c-a5ce-1728ceeffdf; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q; user_persistence=$user_persistence; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1591502380; _gat_UA-77727571-3=1; SLARDAR_WEB_ID=b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1591502380",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1591257799",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNjkzOTQ3MiIsImV4cCI6MTU5NDA5NDM3OSwiaWF0IjoxNTkxNTAyMzc5fQ.bjA5y3gmvyZGgXZnyYvl3Z-D6Oga-093RR61ibf_8EcDuZii1LBgWzbAPwmv4ZPe1HgKVwDX-KHljJP6SSbM8Q",
                    "SESSION": "ab65b4c6-548c-4729-92fa-973de8afe03e",
                    "SLARDAR_WEB_ID": "b1fa988e-6d87-4deb-95d9-d923312022bf",
                    "_ga": "GA1.2.2133272746.1586684123",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.725287396.1591499748",
                    "country": "US",
                    "csrf_token": "33781c0f-249a-4681-ad92-7db4bf319d01",
                    "data-unique-id": "3985b1f0-a873-11ea-a35b-15f69595a402",
                    "data_unique_id": "9e1dc484-873c-43f5-9b4a-b8e13cdba386",
                    "language": "en-US",
                    "mubu_inner": "1",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2Flist",
                    "reg_focusId": "f946fd06-fc70-4a7c-a5ce-1728ceeffdf",
                    "reg_prepareId": "1728ceef558-1728ceef54c-4a7c-a5ce-e34e13cb2f79",
                    "s_v_web_id": "k8wut0a1_ZrNq1ylD_9App_4Vnb_BFt4_V4OwhwKJc5WS",
                    "user_persistence": "$user_persistence",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatedoc().test_start()
