# NOTE: Generated By HttpRunner v3.0.10
# FROM: testcases/mubu_login.yml

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):
    config = (
        Config("testcase description")
        .variables(
            **{
                "user_phone": 18810143184,
                "password": "lm920805",
                "base_url": "https://mubu.com",
            }
        )
        .verify(False)
        .export(*["user_persistence"])
    )

    teststeps = [
        Step(
            RunRequest("/")
            .get("$base_url/")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cache-Control": "max-age=0",
                    "Connection": "keep-alive",
                    "Host": "mubu.com",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()}",
                }
            )
            .validate()
            .assert_equal("status_code", "${expected_status_code(100,100)}")
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/login")
            .get("$base_url/login")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/login/password")
            .get("$base_url/login/password")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/login",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("$base_url/api/login/submit")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "49",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/login/password",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_data(
                {"password": "$password", "phone": "$user_phone", "remember": "true"}
            )
            .extract()
            .with_jmespath("cookies.user_persistence", "user_persistence")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("$base_url/list")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/login/password",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("$base_url/api/list/tip_new_update")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("$base_url/api/list/get")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_data({"folderId": "0", "keywords": "", "sort": "time", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("$base_url/api/message/get_message_unread")
            .with_headers(
                **{
                    "X-Request-ID": "${get_request_id()}",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/list",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
