# NOTICE: Generated By HttpRunner v3.0.8
# FROM: testcases/mubu.createdoc.yml

import os
import sys

sys.path.insert(0, os.getcwd())

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.mubu_login_test import TestCaseMubuLogin as MubuLogin


class TestCaseMubuCreatedoc(HttpRunner):
    config = (
        Config("testcase description")
        .variables(**{"user_phone": 18810143184, "password": "lm920805"})
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("mubu login").call(MubuLogin)),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatedoc().test_start()
